sudo: required
services:
  - docker

before_install:
  - docker build -t mjgwaba/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mjgwaba/react-test npm test -- --coverage

after_success:
  - docker build -t mjgwaba/multi-client ./client
  - docker build -t mjgwaba/multi-nginx ./nginx
  - docker build -t mjgwaba/multi-server ./server
  - docker build -t mjgwaba/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password---password-stdin

  # Push images to docker hub
  - docker push mjgwaba/multi-client
  - docker push mjgwaba/multi-nginx
  - docker push mjgwaba/multi-server
  - docker push mjgwaba/multi-worker